import os

AZURE_BLOB_CONTAINER_NAME = os.getenv('AZURE_BLOB_CONTAINER_NAME')
AZURE_STORAGE_ACCOUNT_NAME = os.getenv("AZURE_STORAGE_ACCOUNT_NAME")
AZURE_STORAGE_ACCOUNT_KEY = os.getenv("AZURE_ACCOUNT_KEY")

# Create the connection string
AZURE_STORAGE_CONNECTION_STRING = (
    f"DefaultEndpointsProtocol=https;AccountName={AZURE_STORAGE_ACCOUNT_NAME};"
    f"AccountKey={AZURE_STORAGE_ACCOUNT_KEY};EndpointSuffix=core.windows.net"
)

JOB_STATUS_PENDING="PENDING"
JOB_STATUS_INPROGRESS="INPROGRESS"
JOB_STATUS_COMPLETED="COMPLETED"
JOB_STATUS_EXCEPTION="EXCEPTION"
JOB_STATUS_PARTIALLY_COMPLETED="PARTIALLY_COMPLETED"